'use client';

import Link from 'next/link';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 bg-zinc-100 dark:bg-zinc-800">
          <ul className="flex space-x-4">
            {/* <li>
              <Link href="/">Home</Link>
            </li> */}
            <li>
              <Link href="/chat">Chat Example</Link>
            </li>
            <li>
              <Link href="/generate-text">Generate Text</Link>
            </li>
            <li>
              <Link href="/generate-object">Generate Object</Link>
            </li>
            <li>
              <Link href="/use-object">stream Object</Link>
            </li>
          </ul>
        </nav>
        <main className="container mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
